// Built-in abbreviation dictionary grouped by domain
export type AbbreviationEntry = {
  abbr: string
  expansion: string
  domain: 'medical' | 'insurance' | 'banking' | 'general' | 'symbols'
}

export const BUILT_IN_ABBREVIATIONS: AbbreviationEntry[] = [
  // ── Medical ────────────────────────────────────────────────────────────────
  { abbr: 'pt',    expansion: 'patient',                   domain: 'medical' },
  { abbr: 'dr',    expansion: 'doctor',                    domain: 'medical' },
  { abbr: 'bp',    expansion: 'blood pressure',            domain: 'medical' },
  { abbr: 'hr',    expansion: 'heart rate',                domain: 'medical' },
  { abbr: 'dob',   expansion: 'date of birth',             domain: 'medical' },
  { abbr: 'dx',    expansion: 'diagnosis',                  domain: 'medical' },
  { abbr: 'rx',    expansion: 'prescription',              domain: 'medical' },
  { abbr: 'sx',    expansion: 'symptoms',                  domain: 'medical' },
  { abbr: 'hx',    expansion: 'history',                   domain: 'medical' },
  { abbr: 'fx',    expansion: 'fracture',                  domain: 'medical' },
  { abbr: 'tx',    expansion: 'treatment',                 domain: 'medical' },
  { abbr: 'px',    expansion: 'prognosis',                 domain: 'medical' },
  { abbr: 'nka',   expansion: 'no known allergies',        domain: 'medical' },
  { abbr: 'nkda',  expansion: 'no known drug allergies',   domain: 'medical' },
  { abbr: 'sob',   expansion: 'shortness of breath',       domain: 'medical' },
  { abbr: 'c/o',   expansion: 'complains of',              domain: 'medical' },
  { abbr: 'ha',    expansion: 'headache',                  domain: 'medical' },
  { abbr: 'abd',   expansion: 'abdomen',                   domain: 'medical' },
  { abbr: 'adm',   expansion: 'admission',                 domain: 'medical' },
  { abbr: 'appt',  expansion: 'appointment',               domain: 'medical' },
  { abbr: 'ref',   expansion: 'referral',                  domain: 'medical' },
  { abbr: 'spec',  expansion: 'specialist',                domain: 'medical' },
  { abbr: 'er',    expansion: 'emergency room',            domain: 'medical' },
  { abbr: 'or',    expansion: 'operating room',            domain: 'medical' },
  { abbr: 'icu',   expansion: 'intensive care unit',       domain: 'medical' },
  { abbr: 'ed',    expansion: 'emergency department',      domain: 'medical' },
  { abbr: 'o2',    expansion: 'oxygen',                    domain: 'medical' },
  { abbr: 'bmi',   expansion: 'body mass index',           domain: 'medical' },
  { abbr: 'wt',    expansion: 'weight',                    domain: 'medical' },
  { abbr: 'ht',    expansion: 'height',                    domain: 'medical' },
  { abbr: 'temp',  expansion: 'temperature',               domain: 'medical' },
  { abbr: 'meds',  expansion: 'medications',               domain: 'medical' },
  { abbr: 'lab',   expansion: 'laboratory test',           domain: 'medical' },
  { abbr: 'surg',  expansion: 'surgery',                   domain: 'medical' },
  { abbr: 'pre-op',expansion: 'pre-operation',             domain: 'medical' },
  { abbr: 'post-op',expansion:'post-operation',            domain: 'medical' },
  { abbr: 'chemo', expansion: 'chemotherapy',              domain: 'medical' },
  { abbr: 'rad',   expansion: 'radiation',                 domain: 'medical' },
  { abbr: 'fup',   expansion: 'follow-up',                 domain: 'medical' },

  // ── Insurance ──────────────────────────────────────────────────────────────
  { abbr: 'ins',   expansion: 'insurance',                 domain: 'insurance' },
  { abbr: 'pol',   expansion: 'policy',                    domain: 'insurance' },
  { abbr: 'polno', expansion: 'policy number',             domain: 'insurance' },
  { abbr: 'ded',   expansion: 'deductible',                domain: 'insurance' },
  { abbr: 'prem',  expansion: 'premium',                   domain: 'insurance' },
  { abbr: 'cov',   expansion: 'coverage',                  domain: 'insurance' },
  { abbr: 'ben',   expansion: 'beneficiary',               domain: 'insurance' },
  { abbr: 'clm',   expansion: 'claim',                     domain: 'insurance' },
  { abbr: 'clmno', expansion: 'claim number',              domain: 'insurance' },
  { abbr: 'eob',   expansion: 'explanation of benefits',   domain: 'insurance' },
  { abbr: 'cop',   expansion: 'copay',                     domain: 'insurance' },
  { abbr: 'coins', expansion: 'coinsurance',               domain: 'insurance' },
  { abbr: 'oop',   expansion: 'out-of-pocket maximum',     domain: 'insurance' },
  { abbr: 'nwk',   expansion: 'network',                   domain: 'insurance' },
  { abbr: 'oon',   expansion: 'out-of-network',            domain: 'insurance' },
  { abbr: 'auth',  expansion: 'authorization',             domain: 'insurance' },
  { abbr: 'pauth', expansion: 'prior authorization',       domain: 'insurance' },
  { abbr: 'hmo',   expansion: 'health maintenance org',    domain: 'insurance' },
  { abbr: 'ppo',   expansion: 'preferred provider org',    domain: 'insurance' },
  { abbr: 'pcp',   expansion: 'primary care physician',    domain: 'insurance' },
  { abbr: 'eff',   expansion: 'effective date',            domain: 'insurance' },
  { abbr: 'exp',   expansion: 'expiration date',           domain: 'insurance' },
  { abbr: 'grp',   expansion: 'group number',              domain: 'insurance' },
  { abbr: 'mbr',   expansion: 'member',                    domain: 'insurance' },
  { abbr: 'mbrno', expansion: 'member ID number',          domain: 'insurance' },

  // ── Banking ────────────────────────────────────────────────────────────────
  { abbr: 'acct',  expansion: 'account',                   domain: 'banking' },
  { abbr: 'acctno',expansion: 'account number',            domain: 'banking' },
  { abbr: 'rtn',   expansion: 'routing number',            domain: 'banking' },
  { abbr: 'bal',   expansion: 'balance',                   domain: 'banking' },
  { abbr: 'xfer',  expansion: 'transfer',                  domain: 'banking' },
  { abbr: 'stmt',  expansion: 'statement',                 domain: 'banking' },
  { abbr: 'int',   expansion: 'interest rate',             domain: 'banking' },
  { abbr: 'wd',    expansion: 'withdrawal',                domain: 'banking' },
  { abbr: 'dep',   expansion: 'deposit',                   domain: 'banking' },
  { abbr: 'chk',   expansion: 'checking',                  domain: 'banking' },
  { abbr: 'sav',   expansion: 'savings',                   domain: 'banking' },
  { abbr: 'cd',    expansion: 'certificate of deposit',    domain: 'banking' },
  { abbr: 'apr',   expansion: 'annual percentage rate',    domain: 'banking' },
  { abbr: 'apy',   expansion: 'annual percentage yield',   domain: 'banking' },
  { abbr: 'pin',   expansion: 'personal ID number',        domain: 'banking' },
  { abbr: 'ssn',   expansion: 'social security number',    domain: 'banking' },
  { abbr: 'dda',   expansion: 'demand deposit account',    domain: 'banking' },
  { abbr: 'ach',   expansion: 'ACH transfer',              domain: 'banking' },
  { abbr: 'wire',  expansion: 'wire transfer',             domain: 'banking' },
  { abbr: 'mtg',   expansion: 'mortgage',                  domain: 'banking' },
  { abbr: 'loan',  expansion: 'loan',                      domain: 'banking' },
  { abbr: 'cc',    expansion: 'credit card',               domain: 'banking' },
  { abbr: 'dc',    expansion: 'debit card',                domain: 'banking' },
  { abbr: 'nsf',   expansion: 'non-sufficient funds',      domain: 'banking' },
  { abbr: 'od',    expansion: 'overdraft',                 domain: 'banking' },

  // ── General / Interpreting ─────────────────────────────────────────────────
  { abbr: 'asap',  expansion: 'as soon as possible',       domain: 'general' },
  { abbr: 'poa',   expansion: 'power of attorney',         domain: 'general' },
  { abbr: 'doa',   expansion: 'date of arrival',           domain: 'general' },
  { abbr: 'addr',  expansion: 'address',                   domain: 'general' },
  { abbr: 'ph',    expansion: 'phone number',              domain: 'general' },
  { abbr: 'zip',   expansion: 'ZIP code',                  domain: 'general' },
  { abbr: 'dpt',   expansion: 'department',                domain: 'general' },
  { abbr: 'ext',   expansion: 'extension',                 domain: 'general' },
  { abbr: 'info',  expansion: 'information',               domain: 'general' },
  { abbr: 'doc',   expansion: 'document',                  domain: 'general' },
  { abbr: 'sig',   expansion: 'signature',                 domain: 'general' },
  { abbr: 'id',    expansion: 'identification',            domain: 'general' },
  { abbr: 'govt',  expansion: 'government',                domain: 'general' },
  { abbr: 'q',     expansion: 'question',                  domain: 'general' },
  { abbr: 'ans',   expansion: 'answer',                    domain: 'general' },
  { abbr: 'imp',   expansion: 'important',                 domain: 'general' },
  { abbr: 'cb',    expansion: 'call back',                 domain: 'general' },
  { abbr: 'conf',  expansion: 'confirmation',              domain: 'general' },
  { abbr: 'confno',expansion: 'confirmation number',       domain: 'general' },

  // ── Symbols ────────────────────────────────────────────────────────────────
  { abbr: '->',    expansion: '→ (leads to)',              domain: 'symbols' },
  { abbr: '=>',    expansion: '⇒ (results in)',            domain: 'symbols' },
  { abbr: 'up',    expansion: '↑ (increase)',              domain: 'symbols' },
  { abbr: 'dn',    expansion: '↓ (decrease)',              domain: 'symbols' },
  { abbr: 'w/',    expansion: 'with',                      domain: 'symbols' },
  { abbr: 'w/o',   expansion: 'without',                   domain: 'symbols' },
  { abbr: 'b/c',   expansion: 'because',                   domain: 'symbols' },
  { abbr: 're',    expansion: 'regarding',                 domain: 'symbols' },
]

export const DOMAIN_LABELS: Record<AbbreviationEntry['domain'], string> = {
  medical:   '🏥 Medical',
  insurance: '🛡 Insurance',
  banking:   '🏦 Banking',
  general:   '📋 General',
  symbols:   '✏️ Symbols',
}

export const DOMAIN_COLORS: Record<AbbreviationEntry['domain'], string> = {
  medical:   '#ef4444',
  insurance: '#3b82f6',
  banking:   '#10b981',
  general:   '#6366f1',
  symbols:   '#f59e0b',
}
