// src/lib/scenarios.ts

export type Scenario = {
  id: string
  title: string
  description: string
  domain: string
  level: 'L2' | 'L3' | 'L4'
  script: string[]
  keyFacts: { label: string; value: string }[]
  glossaryTerms?: string[]
}

export const PRACTICE_EXERCISES: Scenario[] = [
  // ── ORIGINAL 3 ──────────────────────────────────────────────────────────
  {
    id: 'medical',
    title: '🏥 Medical Appointment',
    description: 'A patient calling to schedule, then speaking with a doctor about symptoms.',
    domain: 'medical',
    level: 'L2',
    script: [
      'Receptionist: Good morning, Valley Medical Center. How can I help you?',
      'Patient: Hi, my name is Samuel Tesfaye. I need to schedule an appointment with Dr. Johnson.',
      'Receptionist: Sure. Can I get your date of birth and insurance member ID?',
      'Patient: My date of birth is March 15th, 1985. My member ID is BCA-447821.',
      'Receptionist: And what is the reason for your visit today?',
      'Patient: I have been having shortness of breath and chest pain for about three days.',
      'Receptionist: Okay. We have an opening this Thursday at 2:30 PM. Does that work?',
      'Patient: Yes, that works. My phone number is 617-555-0193.',
      'Receptionist: Great. Your confirmation number is MED-20940. Please bring your insurance card.',
    ],
    keyFacts: [
      { label: 'Patient name', value: 'Samuel Tesfaye' },
      { label: 'DOB', value: 'March 15, 1985' },
      { label: 'Member ID', value: 'BCA-447821' },
      { label: 'Symptoms', value: 'Shortness of breath, chest pain' },
      { label: 'Appointment', value: 'Thursday 2:30 PM' },
      { label: 'Phone', value: '617-555-0193' },
      { label: 'Confirmation #', value: 'MED-20940' },
    ],
    glossaryTerms: ['prescription', 'diagnosis', 'symptom', 'insurance', 'referral'],
  },
  {
    id: 'insurance',
    title: '🛡️ Insurance Claim Call',
    description: 'A client filing a car accident claim with their insurance company.',
    domain: 'insurance',
    level: 'L2',
    script: [
      'Agent: Thank you for calling Horizon Insurance. My name is Lisa. How can I assist you?',
      'Caller: I need to file a claim for a car accident I had on Sunday.',
      'Agent: I am sorry to hear that. Can I have your policy number?',
      'Caller: Yes, it is PPO-33-77614.',
      'Agent: And your full name and date of birth?',
      'Caller: Miriam Alemu, date of birth July 4th, 1978.',
      'Agent: Thank you. Was anyone injured?',
      'Caller: No, just property damage. The repair estimate is about four thousand dollars.',
      'Agent: I will open a claim. Your claim number is CLM-2026-8844. Someone will contact you within 3 business days.',
      'Caller: What is your name and direct extension?',
      'Agent: Lisa Carter, extension 4412.',
    ],
    keyFacts: [
      { label: 'Policy number', value: 'PPO-33-77614' },
      { label: 'Client name', value: 'Miriam Alemu' },
      { label: 'DOB', value: 'July 4, 1978' },
      { label: 'Damage estimate', value: '$4,000' },
      { label: 'Claim number', value: 'CLM-2026-8844' },
      { label: 'Agent', value: 'Lisa Carter, ext. 4412' },
    ],
    glossaryTerms: ['policy', 'claim', 'property damage', 'deductible'],
  },
  {
    id: 'banking',
    title: '🏦 Bank Account Dispute',
    description: 'A customer disputing an unrecognized charge and transferring funds.',
    domain: 'banking',
    level: 'L2',
    script: [
      'Bank rep: Welcome to FirstBank customer service. My name is Daniel.',
      'Customer: Hi Daniel. I am calling about my checking account. There is a charge I do not recognize.',
      'Bank rep: I can look into that. Can I have your account number for verification?',
      'Customer: Sure. My account number is 0083-4421-99.',
      'Bank rep: And your full name and last four digits of your social security number?',
      'Customer: Abebe Girma, last four 3-8-7-2.',
      'Bank rep: Thank you. I can see a charge on March 20th for $248 from OnlineShop LLC. Do you recognize that?',
      'Customer: No, I do not. I want to dispute it.',
      'Bank rep: I will open a dispute. The dispute reference number is DSP-441899. Also, would you like to transfer your available balance to savings as a precaution?',
      'Customer: Yes please. My savings account routing number is 021000089.',
      'Bank rep: The transfer of $1,340 has been initiated. It will post within one business day.',
    ],
    keyFacts: [
      { label: 'Account number', value: '0083-4421-99' },
      { label: 'Customer name', value: 'Abebe Girma' },
      { label: 'SSN last 4', value: '3872' },
      { label: 'Disputed charge', value: '$248 from OnlineShop LLC, March 20' },
      { label: 'Dispute reference', value: 'DSP-441899' },
      { label: 'Routing number', value: '021000089' },
      { label: 'Transfer amount', value: '$1,340' },
    ],
    glossaryTerms: ['routing number', 'fraud', 'dispute', 'debit card', 'overdraft'],
  },

  // ── 7 NEW SCENARIOS ──────────────────────────────────────────────────────
  {
    id: 'mental-health',
    title: '🧠 Mental Health Assessment',
    description: 'A therapist conducting an intake mental health evaluation with a new patient.',
    domain: 'medical',
    level: 'L3',
    script: [
      'Therapist: Good afternoon. I am Dr. Rivera, I will be conducting your intake evaluation today. Can you tell me what brought you in?',
      'Patient: I have been feeling very anxious and I have not been sleeping well for the past two months.',
      'Therapist: I understand. On a scale of one to ten, how would you rate your anxiety most days?',
      'Patient: I would say about a seven or eight. I have panic attacks sometimes.',
      'Therapist: Have you experienced any thoughts of harming yourself or others?',
      'Patient: No, nothing like that. I just feel overwhelmed all the time.',
      'Therapist: Are you currently taking any medications, prescribed or over the counter?',
      'Patient: Only vitamins. My primary doctor, Dr. Haile, suggested I come see you.',
      'Therapist: Have you ever received mental health treatment before?',
      'Patient: Yes, I saw a counselor back home in Ethiopia about five years ago after a loss in the family.',
      'Therapist: Thank you for sharing that. I am going to recommend weekly therapy sessions and I would like to refer you to our psychiatry team for a medication evaluation.',
      'Patient: Will my insurance cover this? I have Medicaid.',
      'Therapist: Yes, Medicaid covers our services. Our scheduler will call you within two business days to set up your appointments.',
    ],
    keyFacts: [
      { label: 'Provider', value: 'Dr. Rivera' },
      { label: 'Referral from', value: 'Dr. Haile (primary)' },
      { label: 'Anxiety rating', value: '7–8 out of 10' },
      { label: 'Symptoms', value: 'Anxiety, insomnia, panic attacks' },
      { label: 'SI/HI', value: 'Denied' },
      { label: 'Insurance', value: 'Medicaid' },
      { label: 'Plan', value: 'Weekly therapy + psychiatry referral' },
    ],
    glossaryTerms: ['anxiety', 'panic attack', 'intake evaluation', 'psychiatry', 'Medicaid', 'referral', 'counselor'],
  },
  {
    id: 'custody',
    title: '⚖️ Custody Hearing Briefing',
    description: 'An attorney explaining a custody hearing to their client before court.',
    domain: 'legal',
    level: 'L3',
    script: [
      'Attorney: Good morning. I am your attorney, Ms. Chen. We have about 15 minutes before the hearing begins.',
      'Client: Thank you. I am very nervous. What will happen today?',
      'Attorney: Today is a temporary custody hearing. The judge will decide who the child lives with until the final hearing in June.',
      'Client: Can I speak directly to the judge?',
      'Attorney: You may be asked to speak, but I will be doing most of the talking. Please only answer what is asked and keep your answers brief.',
      'Client: What is the other side asking for?',
      'Attorney: The respondent is requesting primary physical custody. We are asking for joint legal and physical custody with a 50-50 parenting plan.',
      'Client: What does joint legal custody mean?',
      'Attorney: It means both parents share decision-making for the child — school, medical care, religion.',
      'Client: And if the judge rules against me today?',
      'Attorney: We can appeal, and the final hearing in June will be a full trial where we present all of our evidence.',
      'Client: I understand. Thank you.',
      'Attorney: One more thing — please do not speak to the other party or their attorney in the courtroom.',
    ],
    keyFacts: [
      { label: 'Attorney', value: 'Ms. Chen' },
      { label: 'Hearing type', value: 'Temporary custody' },
      { label: 'Petitioner request', value: 'Joint legal and physical custody, 50-50' },
      { label: 'Respondent request', value: 'Primary physical custody' },
      { label: 'Final hearing', value: 'June (full trial)' },
    ],
    glossaryTerms: ['custody', 'temporary custody', 'joint legal custody', 'parenting plan', 'respondent', 'appeal', 'hearing'],
  },
  {
    id: 'eviction',
    title: '🏠 Eviction Notice Call',
    description: 'A housing case worker helping a tenant understand an eviction notice.',
    domain: 'social services',
    level: 'L2',
    script: [
      'Case worker: Hello, this is Maria from the Tenant Resource Center. I understand you received an eviction notice?',
      'Tenant: Yes. I received it two days ago. I do not understand what it says.',
      'Case worker: Can you read me the date that is listed at the top of the notice?',
      'Tenant: It says March 18th. It says I have 30 days.',
      'Case worker: This is a 30-day notice to pay or quit. It means you must pay the overdue rent or move out within 30 days.',
      'Tenant: How much do I owe?',
      'Case worker: The notice should list the amount. What does it say?',
      'Tenant: It says $1,850.',
      'Case worker: Okay. Have you applied for any emergency rental assistance?',
      'Tenant: No. I did not know that was available.',
      'Case worker: I am going to give you the number for the Emergency Housing Assistance Program. Their number is 1-800-541-2000.',
      'Tenant: Can they pay my landlord directly?',
      'Case worker: Yes. If approved, they pay the landlord directly and it stops the eviction process. You need to apply before your 30 days run out.',
      'Tenant: Thank you. I will call them today.',
    ],
    keyFacts: [
      { label: 'Notice type', value: '30-day pay or quit' },
      { label: 'Notice date', value: 'March 18' },
      { label: 'Amount owed', value: '$1,850' },
      { label: 'Assistance program', value: 'Emergency Housing Assistance Program' },
      { label: 'Program phone', value: '1-800-541-2000' },
    ],
    glossaryTerms: ['eviction', 'pay or quit', 'rental assistance', 'overdue rent', 'landlord'],
  },
  {
    id: 'immigration-court',
    title: '🏛️ Immigration Court Check-in',
    description: 'An immigration attorney preparing a client for their court master hearing.',
    domain: 'immigration',
    level: 'L4',
    script: [
      'Attorney: Good morning, Mr. Bekele. Today is your master calendar hearing. This is not your full trial — it is just to set your court dates.',
      'Client: I understand. Will the judge ask me about my case today?',
      'Attorney: The judge may ask if you are applying for asylum. You should say yes.',
      'Client: What if I am asked about why I left Ethiopia?',
      'Attorney: Today is not the time for your full story. Simply say you are seeking asylum and that your attorney will present your full case at the individual hearing.',
      'Client: When is the individual hearing?',
      'Attorney: We do not have the date yet. The judge will set it today. It could be six to twelve months from now.',
      'Client: What if I miss the hearing?',
      'Attorney: If you miss any hearing without notifying me, the judge can order your removal in absentia. You must always appear.',
      'Client: I understand. What should I bring today?',
      'Attorney: Your passport, your I-94 arrival record, and your notice to appear — that is the document that started your case.',
      'Client: I have all of those.',
      'Attorney: Good. One more thing — all of your responses must go through me. Do not answer any question directly to the judge without my guidance.',
    ],
    keyFacts: [
      { label: 'Hearing type', value: 'Master calendar hearing' },
      { label: 'Relief sought', value: 'Asylum' },
      { label: 'Next hearing', value: 'Individual hearing (6–12 months)' },
      { label: 'Documents needed', value: 'Passport, I-94, Notice to Appear' },
      { label: 'Risk', value: 'Removal in absentia if missed' },
    ],
    glossaryTerms: ['asylum', 'master calendar hearing', 'individual hearing', 'removal in absentia', 'I-94', 'notice to appear'],
  },
  {
    id: 'loan',
    title: '💰 Loan Application Call',
    description: 'A bank loan officer taking a client through a personal loan application.',
    domain: 'banking',
    level: 'L2',
    script: [
      'Loan officer: Good afternoon, thank you for calling Community Bank. My name is James. I understand you are interested in a personal loan?',
      'Customer: Yes. I need to borrow money to pay for medical bills.',
      'Loan officer: I can help you with that. How much are you looking to borrow?',
      'Customer: About eight thousand dollars.',
      'Loan officer: And what is your approximate monthly income before taxes?',
      'Customer: Around three thousand two hundred dollars per month.',
      'Loan officer: Do you have any existing loans or monthly debt payments?',
      'Customer: I have a car payment of $310 a month.',
      'Loan officer: Do you know your approximate credit score?',
      'Customer: I checked last month and it was 658.',
      'Loan officer: Okay. Based on what you have told me, you may qualify for a loan at an interest rate between 12 and 16 percent, with a 36-month term. Would you like to submit a full application?',
      'Customer: Yes, please. What documents do I need?',
      'Loan officer: You will need your most recent two pay stubs, a government-issued ID, and your bank account number.',
      'Customer: I can get all of those. How long does approval take?',
      'Loan officer: Typically 2 to 3 business days once we have all your documents.',
    ],
    keyFacts: [
      { label: 'Loan amount', value: '$8,000' },
      { label: 'Purpose', value: 'Medical bills' },
      { label: 'Monthly income', value: '$3,200 (gross)' },
      { label: 'Car payment', value: '$310/month' },
      { label: 'Credit score', value: '658' },
      { label: 'Interest rate range', value: '12–16%' },
      { label: 'Term', value: '36 months' },
      { label: 'Approval time', value: '2–3 business days' },
    ],
    glossaryTerms: ['personal loan', 'credit score', 'interest rate', 'monthly income', 'debt', 'collateral', 'term'],
  },
  {
    id: 'er-triage',
    title: '🚑 Emergency Room Triage',
    description: 'An ER nurse conducting a rapid triage assessment of a new patient.',
    domain: 'medical',
    level: 'L3',
    script: [
      'Nurse: Hello, I am Nurse Williams. I need to ask you some quick questions. What brings you in today?',
      'Patient: My husband. He fell and hit his head. He was unconscious for a few seconds.',
      'Nurse: How long ago did this happen?',
      'Patient: About 45 minutes ago. He is confused now.',
      'Nurse: Is he on any blood thinners or anticoagulant medications?',
      'Patient: Yes. He takes warfarin every day. 5 milligrams.',
      'Nurse: Does he have any known allergies to medications?',
      'Patient: He is allergic to penicillin.',
      'Nurse: What is his date of birth?',
      'Patient: September 3rd, 1951.',
      'Nurse: Has he vomited or complained of a severe headache since the fall?',
      'Patient: Yes, he vomited once in the car.',
      'Nurse: Okay. This is a priority case. We are going to take him to get a CT scan of his head right away.',
      'Patient: Is he going to be okay?',
      'Nurse: The doctor will explain everything after the scan. We are going to take very good care of him.',
    ],
    keyFacts: [
      { label: 'Chief complaint', value: 'Head trauma, brief loss of consciousness' },
      { label: 'Time of incident', value: '~45 minutes ago' },
      { label: 'Current status', value: 'Confused' },
      { label: 'Medications', value: 'Warfarin 5mg daily' },
      { label: 'Allergy', value: 'Penicillin' },
      { label: 'DOB', value: 'September 3, 1951' },
      { label: 'Symptoms', value: 'Vomited once, confusion' },
      { label: 'Next step', value: 'CT scan (priority)' },
    ],
    glossaryTerms: ['triage', 'anticoagulant', 'warfarin', 'allergy', 'CT scan', 'loss of consciousness', 'penicillin'],
  },
  {
    id: 'benefits',
    title: '📋 Social Services Benefits Review',
    description: 'A benefits specialist reviewing a client\'s SNAP and Medicaid eligibility.',
    domain: 'social services',
    level: 'L2',
    script: [
      'Specialist: Hello, my name is Angela from the Department of Health and Human Services. Am I speaking with Hana Tadesse?',
      'Client: Yes, this is Hana.',
      'Specialist: We are calling to do your annual review for your SNAP and Medicaid benefits. This should take about 10 minutes. Is now a good time?',
      'Client: Yes, that is fine.',
      'Specialist: Has your household size changed in the last 12 months?',
      'Client: Yes. My mother moved in with me in January. So now there are four people: myself, two children, and my mother.',
      'Specialist: And has your income changed?',
      'Client: I started a part-time job in February. I make about $900 a month.',
      'Specialist: Does anyone else in the household have income?',
      'Client: My mother receives Social Security. She gets $820 a month.',
      'Specialist: Do you have any child support or alimony coming in?',
      'Client: No.',
      'Specialist: Thank you. Based on your household size of four and your total monthly income of about $1,720, you appear to still be eligible for both Medicaid and SNAP. I will send you a renewal letter in the mail within 10 days.',
      'Client: Do I need to send anything back?',
      'Specialist: If the information on the letter is correct, just sign and return it. If anything has changed, mark the changes and include a copy of your pay stubs.',
    ],
    keyFacts: [
      { label: 'Client name', value: 'Hana Tadesse' },
      { label: 'Review type', value: 'Annual — SNAP + Medicaid' },
      { label: 'Household size', value: '4 (client, 2 children, mother)' },
      { label: 'Client income', value: '$900/month (part-time, since Feb)' },
      { label: 'Mother income', value: '$820/month (Social Security)' },
      { label: 'Total household income', value: '~$1,720/month' },
      { label: 'Eligibility', value: 'Still eligible for SNAP + Medicaid' },
      { label: 'Next step', value: 'Renewal letter mailed within 10 days' },
    ],
    glossaryTerms: ['SNAP', 'Medicaid', 'household size', 'annual review', 'Social Security', 'eligibility', 'income'],
  },
]
